services:
  web:
    build:
      context: ./app
    ports:
      - "5183:5000"
    restart: always
    env_file: ".env"
    # environment:
    #   FLASK_ENV: development
    #   FLASK_APP: main.py
    #   SECRET_KEY: "My 5UP3r S3cR6t k3Y"
    #   DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    #   REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app

  db:
    image: postgres:13
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6382:6379"
    volumes:
      - ./redis_data:/data
