services:
  web:
    build:
      context: ./app
    ports:
      - "5183:5000"
    restart: always
    env_file: ".env"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app

  db:
    image: postgres:13
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6382:6379"
    volumes:
      - ./redis_data:/data
